name: Clojure
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/clojure.yml
      - languages/clojure/**
  schedule:
    - cron:  15 3 * * MON
  workflow_dispatch:
jobs:
  version:
    strategy:
      matrix:
        version: ["latest"]
    name: "${{ matrix.version }}"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "${{ matrix.version }}"
      language: clojure
      description: Devcontainer for Clojure with clojure-lsp
    secrets: inherit
