name: Crystal
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/crystal.yml
      - languages/crystal/**
  schedule:
    - cron:  25 3 * * MON
  workflow_dispatch:
jobs:
  version:
    strategy:
      matrix:
        version: ["latest"]
    name: "${{ matrix.version }}"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "${{ matrix.version }}"
      language: crystal
      description: Devcontainer for Crystal with Crystalline
    secrets: inherit
