name: Elixir
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/elixir.yml
      - languages/elixir/**
  schedule:
    - cron:  35 3 * * MON
  workflow_dispatch:
jobs:
  version:
    strategy:
      matrix:
        version: ["latest", "1.16", "1.15", "1.14", "1.13"]
    name: "${{ matrix.version }}"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "${{ matrix.version }}"
      language: elixir
      description: Devcontainer for Elixir with ElixirLS
    secrets: inherit
