name: Erlang
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/erlang.yml
      - languages/erlang/**
  schedule:
    - cron:  45 3 * * MON
jobs:
  version:
    strategy:
      matrix:
        version: ["latest", "26", "25", "24", "23"]
    name: "${{ matrix.version }}"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "${{ matrix.version }}"
      language: erlang
      description: Devcontainer for Erlang with Erlang LS
    secrets: inherit
