name: Go
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/go.yml
      - languages/go/**
  schedule:
    - cron:  55 3 * * MON
jobs:
  version:
    strategy:
      matrix:
        version: ["latest", "1.19", "1.18"]
    name: "${{ matrix.version }}"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "${{ matrix.version }}"
      language: go
      description: Devcontainer for Go with gopls
    secrets: inherit
