name: GraalVM
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/graalvm.yml
      - languages/graalvm/**
  schedule:
    - cron:  15 4 * * MON
jobs:
  version:
    strategy:
      matrix:
        version: ["latest", "21", "17"]
    name: "${{ matrix.version }}"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "${{ matrix.version }}"
      language: graalvm
      description: Devcontainer for GraalVM with JDT LS
    secrets: inherit
