name: Haskell
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/haskell.yml
      - languages/haskell/**
  schedule:
    - cron:  25 4 * * MON
jobs:
  version:
    strategy:
      matrix:
        version: ["latest", "9.4", "9.2", "9.0", "8.10"]
    name: "${{ matrix.version }}"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "${{ matrix.version }}"
      language: haskell
      description: Devcontainer for Haskell with Haskell Language Server
    secrets: inherit
