name: Julia
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/julia.yml
      - languages/julia/**
  schedule:
    - cron:  45 4 * * MON
jobs:
  version:
    strategy:
      matrix:
        version: ["latest", "1.8", "1.6"]
    name: "${{ matrix.version }}"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "${{ matrix.version }}"
      language: julia
      description: Devcontainer for Julia with Julia Language Server
    secrets: inherit
