name: Nim
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/nim.yml
      - languages/nim/**
  schedule:
    - cron:  55 4 * * MON
  workflow_dispatch:
jobs:
  version:
    strategy:
      matrix:
        version: ["latest"]
    name: "${{ matrix.version }}"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "${{ matrix.version }}"
      language: nim
      description: Devcontainer for Nim with Nim Language Server
    secrets: inherit
