name: NodeJS
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/nodejs.yml
      - languages/nodejs/**
  schedule:
    - cron:  25 5 * * MON
jobs:
  version:
    strategy:
      matrix:
        version: ["latest", "20", "18"]
    name: "${{ matrix.version }}"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "${{ matrix.version }}"
      language: nodejs
      description: Devcontainer for NodeJS with TypeScript Language Server
    secrets: inherit
