name: Perl
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/perl.yml
      - languages/perl/**
  schedule:
    - cron:  35 5 * * MON
  workflow_dispatch:
jobs:
  version:
    strategy:
      matrix:
        version: ["latest"]
    name: "${{ matrix.version }}"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "${{ matrix.version }}"
      language: perl
      description: Devcontainer for Perl with Perl Language Server
    secrets: inherit
