name: Prolog
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/prolog.yml
      - languages/prolog/**
  schedule:
    - cron:  45 5 * * MON
  workflow_dispatch:
jobs:
  version:
    strategy:
      matrix:
        version: ["latest", "stable"]
    name: "${{ matrix.version }}"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "${{ matrix.version }}"
      language: prolog
      description: Devcontainer for Prolog with Prolog Language Server
    secrets: inherit
