name: Publish Container Image
on:
  workflow_call:
    inputs:
      language:
        type: string
        description: The programming language of the devcontainer
        required: true
      version:
        type: string
        description: The version of the devcontainer
        required: true
      description:
        type: string
        description: The short description for dockerhub
        required: true
      repository:
        type: string
        description: The dockerhub repository to use
        default: metio/devcontainers
        required: false
      license:
        type: string
        description: The license of the container
        default: CC0-1.0
        required: false
      vendor:
        type: string
        description: The vendor of the container
        default: metio.wtf
        required: false
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      security-events: write
    outputs:
      digest: ${{ steps.publish.outputs.digest }}
    steps:
      - id: checkout
        name: Checkout Code
        uses: actions/checkout@v3
      - id: cosign-install
        name: Install Cosign
        uses: sigstore/cosign-installer@main
      - id: syft-install
        name: Install Syft
        uses: anchore/sbom-action/download-syft@v0.13.1
      - id: grype-install
        name: Install Grype
        uses: anchore/scan-action/download-grype@v3
      - id: buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - id: dockerhub_login
        name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - id: timestamp
        name: Create Timestamp
        run: echo "date=$(date --rfc-3339=seconds)" >> $GITHUB_OUTPUT
      - id: publish
        name: Publish Image
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./languages/${{ inputs.language }}/${{ inputs.version }}/
          file: ./languages/${{ inputs.language }}/${{ inputs.version }}/Containerfile
          push: true
          tags: docker.io/${{ inputs.repository }}-${{ inputs.language }}:${{ inputs.version }}
          labels: |
            org.opencontainers.image.title=${{ inputs.language }}
            org.opencontainers.image.description=Image for ${{ inputs.language }} development
            org.opencontainers.image.licenses=${{ inputs.license }}
            org.opencontainers.image.vendor=${{ inputs.vendor }}
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.documentation=https://github.com/${{ github.repository }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}/languages/${{ inputs.language }}/${{ inputs.version }}
            org.opencontainers.image.version=${{ inputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.timestamp.outputs.date }}
          cache-from: type=registry,ref=${{ inputs.repository }}-${{ inputs.language }}:buildcache
          cache-to: type=registry,ref=${{ inputs.repository }}-${{ inputs.language }}:buildcache,mode=max
      - id: sign
        name: Sign Image
        run: cosign sign docker.io/${{ inputs.repository }}-${{ inputs.language }}@${{ steps.publish.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: "true"
      - id: sbom
        name: Generate SBOM
        run: syft docker.io/${{ inputs.repository }}-${{ inputs.language }}@${{ steps.publish.outputs.digest }} -o spdx-json=sbom-spdx.json
      - id: sbom-attest
        name: Attest SBOM
        run: |
          cosign attest \
            --predicate sbom-spdx.json \
            --type spdx \
            docker.io/${{ inputs.repository }}-${{ inputs.language }}@${{ steps.publish.outputs.digest }}
        env:
          COSIGN_EXPERIMENTAL: "true"
      - id: grype-scan
        name: Scan SBOM with Grype
        run: |
          grype -o sarif --only-fixed sbom:sbom-spdx.json > grype.sarif
          jq '.runs[].tool.driver.name |= "grype-${{ inputs.language }}-${{ inputs.version }}"' grype.sarif > grype-${{ inputs.language }}-${{ inputs.version }}.sarif
      - id: hadolint-scan
        name: Scan Containerfile with Hadolint
        uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: ./languages/${{ inputs.language }}/${{ inputs.version }}/Containerfile
          format: sarif
          output-file: hadolint.sarif
          no-fail: true
      - id: hadolint-sarif
        name: Adjust Hadolint SARIF Report
        run: jq '.runs[].tool.driver.name |= "hadolint-${{ inputs.language }}-${{ inputs.version }}"' hadolint.sarif > hadolint-${{ inputs.language }}-${{ inputs.version }}.sarif
      - id: grype-upload
        name: Upload Grype SARIF Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: grype-${{ inputs.language }}-${{ inputs.version }}.sarif
          category: grype-${{ inputs.language }}-${{ inputs.version }}
      - id: hadolint-upload
        name: Upload Hadolint SARIF Report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint-${{ inputs.language }}-${{ inputs.version }}.sarif
          category: hadolint-${{ inputs.language }}-${{ inputs.version }}
      - id: documentation
        name: Docker Hub Description
        if: ${{ inputs.version }} == "latest"
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ inputs.repository }}-${{ inputs.language }}
          short-description: ${{ inputs.description }}
          readme-filepath: ./languages/${{ inputs.language }}/README.md
  provenance:
    needs: [publish]
    permissions:
      actions: read
      id-token: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.4.0
    with:
      image: docker.io/${{ inputs.repository }}-${{ inputs.language }}
      digest: ${{ needs.publish.outputs.digest }}
      registry-username: ${{ secrets.DOCKER_USERNAME }}
    secrets:
      registry-password: ${{ secrets.DOCKER_PASSWORD }}
