name: Python
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/python.yml
      - languages/python/**
  schedule:
    - cron:  55 5 * * MON
jobs:
  version:
    strategy:
      matrix:
        version: ["latest", "3.11", "3.10", "3.9", "3.8", "3.7"]
    name: "${{ matrix.version }}"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "${{ matrix.version }}"
      language: python
      description: Devcontainer for Python with Python Language Server
    secrets: inherit
