name: R
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/r.yml
      - languages/r/**
  schedule:
    - cron:  15 6 * * MON
  workflow_dispatch:
jobs:
  version:
    strategy:
      matrix:
        version: ["latest"]
    name: "${{ matrix.version }}"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "${{ matrix.version }}"
      language: r
      description: Devcontainer for R with R Language Server
    secrets: inherit
