name: Ruby
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/ruby.yml
      - languages/ruby/**
  schedule:
    - cron:  25 6 * * MON
  workflow_dispatch:
jobs:
  version:
    strategy:
      matrix:
        version: ["latest"]
    name: "${{ matrix.version }}"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "${{ matrix.version }}"
      language: ruby
      description: Devcontainer for Ruby with Ruby Language Server
    secrets: inherit
