name: Rust
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish-image.yml
      - .github/workflows/rust.yml
      - languages/rust/**
  schedule:
    - cron:  35 6 * * MON
jobs:
  version:
    strategy:
      matrix:
        version: ["latest"]
    name: "${{ matrix.version }}"
    uses: ./.github/workflows/publish-image.yml
    with:
      version: "${{ matrix.version }}"
      language: rust
      description: Devcontainer for Rust with rust-analyzer
    secrets: inherit
